# Generated by Django 3.1.2 on 2021-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
