# Generated by Django 3.1.2 on 2021-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210503_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
