# Generated by Django 3.1.2 on 2021-05-07 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 13, 24, 9, 597427)),
        ),
        migrations.AddField(
            model_name='addpost',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
