# Generated by Django 3.1.2 on 2021-05-08 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210507_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 15, 3, 55, 817671)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 15, 3, 55, 819703))),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.addpost')),
            ],
        ),
    ]
