# Generated by Django 3.1.2 on 2021-05-08 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210508_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 18, 12, 28, 312881)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 18, 12, 28, 315964)),
        ),
    ]
