# Generated by Django 3.1.2 on 2021-05-10 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210509_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='email',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addpost',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 15, 29, 27, 623674)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 15, 29, 27, 625671)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.registration'),
        ),
    ]
