# Generated by Django 3.1.2 on 2021-05-10 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210510_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='like',
        ),
        migrations.AlterField(
            model_name='addpost',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
