# Generated by Django 3.1.2 on 2021-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210510_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='dislike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpost',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
