from django.urls import path,re_path
from . import views

urlpatterns = [
    path('', views.index,name="index"),
    path('register',views.register,name="register"),
    path("login",views.login,name="login"),
    path("logout",views.logout,name="logout"),
    path("profile",views.profile,name="logout"),
    path("addpost",views.add_post,name="addpost"),
    path("remove_profile",views.remove_profile,name="remove_profile"),
    path("like/<int:post_id>/<int:counter>",views.like,name="like"),
    path("dislike/<int:post_id>/<int:counter>",views.dislike,name="dislike"),
    path("make_friends/<str:ka>/<str:counter>",views.make_friends,name="makefriends"),
    path("follow_request",views.follow_request,name="follow_request"),
    path("requested",views.requested,name="requested"),
    path("confirm_request/<str:username>",views.confirm_request,name="confirm"),
    path("myfriends",views.myfriends,name="myfriends"),
    path("delete_request/<str:username>/<int:po>",views.delete_request,name="delete"),
    path("view_profile/<str:username>",views.view_profile,name="view_profile"),
    path("user_post/<str:username>",views.user_post,name="user_post"),
    path("view_post/<int:id>",views.view_post,name="view_post"),
    path("view_friends/<str:username>",views.view_friends,name="view_friend"),
    path("top_post",views.top_post,name="top_post"),
    path("my_post",views.my_post,name="my_post"),
    path("edit_post/<int:id>",views.edit_post,name="edit_post"),
    path("remove_friend/<str:username>",views.remove_friend,name="remove_friend"),
    path("view_comment",views.view_comment,name="view_comment"),
    path("comment",views.comment,name="comment"),
    path("search",views.search,name="search"),
    path("search_related",views.search_related,name="search_related"),
    path("search_user",views.search_user,name="search_user"),
    path("search_related_name",views.search_related_name,name="search_related_name"),
    path("change_password",views.change_password,name="change_password"),
    path("delete_user/<str:email>",views.delete_user,name="user_delete"),
    path("delete_post/<int:id>",views.delete_post,name="delete_post"),
]